/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#FF6B35',
        secondary: '#F7931E',
        accent: '#FDB833',
        'primary-50': 'hsl(var(--color-primary-50))',
        'primary-100': 'hsl(var(--color-primary-100))',
        'primary-500': 'hsl(var(--color-primary-500))',
        'primary-600': 'hsl(var(--color-primary-600))',
        'primary-700': 'hsl(var(--color-primary-700))',
        'secondary-500': 'hsl(var(--color-secondary-500))',
        'secondary-600': 'hsl(var(--color-secondary-600))',
        slate: {
          50: 'hsl(var(--color-slate-50))',
          100: 'hsl(var(--color-slate-100))',
          200: 'hsl(var(--color-slate-200))',
          300: 'hsl(var(--color-slate-300))',
          400: 'hsl(var(--color-slate-400))',
          500: 'hsl(var(--color-slate-500))',
          600: 'hsl(var(--color-slate-600))',
          700: 'hsl(var(--color-slate-700))',
          800: 'hsl(var(--color-slate-800))',
          900: 'hsl(var(--color-slate-900))',
          950: 'hsl(var(--color-slate-950))',
        },
        success: 'hsl(var(--color-success))',
        'success-50': 'hsl(var(--color-success-50))',
        'success-100': 'hsl(var(--color-success-100))',
        'success-500': 'hsl(var(--color-success-500))',
        'success-600': 'hsl(var(--color-success-600))',
        destructive: 'hsl(var(--color-destructive))',
        'destructive-50': 'hsl(var(--color-destructive-50))',
        'destructive-500': 'hsl(var(--color-destructive-500))',
        'destructive-600': 'hsl(var(--color-destructive-600))',
        warning: 'hsl(var(--color-warning))',
        'warning-500': 'hsl(var(--color-warning-500))',
        background: 'hsl(var(--color-background))',
        'background-secondary': 'hsl(var(--color-background-secondary))',
        card: 'hsl(var(--color-card))',
        accent: 'hsl(var(--color-accent))',
'accent-foreground': 'var(--color-button-text)',
        muted: 'hsl(var(--color-muted))',
        'muted-foreground': 'hsl(var(--color-muted-foreground))',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
